### ISSUE TITLE
Using the fileRenameFunction changes "File" to "Blob"

### ISSUE THREAD

**Issue by redfellow** [pqina/filepond-plugin-file-rename#15]
Simply initing filePond with `fileRenameFunction: function(file) { return file.name }` changes how the file appears in formData.

![image](https://user-images.githubusercontent.com/1110164/129937152-0c1b8746-178d-44e3-b884-d07dc9e7e218.png)

Should look like this (no function set):
![image](https://user-images.githubusercontent.com/1110164/129937250-9d037496-a378-4940-a5db-9a0f74a5107e.png)

The renaming does work UI-wise, the preview box has the correct filename, it's just when starting the actual upload, things break.

Output of `pond.getFiles()` when function is in use:

![image](https://user-images.githubusercontent.com/1110164/129937580-b8e51cda-7cb7-4c1f-8ab4-88af0a7a3f00.png)

And when not in use:

![image](https://user-images.githubusercontent.com/1110164/129937771-65d2891a-22d4-4e6a-8144-c1b0be25d15b.png)

So from quick look, it looks like when renamer is in use, the file object in getfiles is actually a blob and not a File (instance of a blob)?

Any way to fix this?

**Comment by rikschennink** [comment]
How are you uploading the file?

(it turns it into a blob because file constructor isn't supported on old IE)

**Comment by redfellow** [comment]
```js
server: {
	process: component.processFile,
}
```

And the upload logic is our own. It's basically and endpoint that eats multiple `formData` objects containing a `File` each.

Snip:

```js
			var xhr = new XMLHttpRequest();

			xhr.open("POST", parameters.serviceurl, true);

			xhr.onload = function (error) {
				...
			};

			xhr.upload.onprogress = function (e) {
				...
			};

			xhr.onerror = function (error) {
				...
			}

	
			xhr.send(formData);
```

The `File` object limitation/requirement comes from the server side. We could perhaps work around this. It's still confusing as to why the rename plugin turns the `File` object inside fileponds `getFiles` to a `Blob`.

Edit: I might of just now understood your comment, the renaming of a file creates a new File, but since this isn't supported on IE, the renamer uses just a Blob for compatability?

**Comment by rikschennink** [comment]
Because renaming a file requires creating a new file. https://pqina.nl/blog/rename-a-file-with-javascript/

How are you creating the `formData`, the approach below should work.

```js
const formData = new FormData();
formData.append(fieldName, file, file.name);
```

**Comment by redfellow** [comment]
Thanks for setting me on correct path. I refactored the upload logic to use that style of formData.append vs. just key/value that we had.
