### ISSUE TITLE
pass uploader instance to the function

### ISSUE THREAD

**Issue by lekoala** [pqina/filepond-plugin-file-rename#2]
hey!

i'm looking into having dynamic renaming function (basically, I define it once, then inspect the uploader to rename files according to patterns.

To do that, it would be great to pass the uploader instance to fileRenameFunction. Something like
fileRenameFunction: function(file, uploader) { ... }

Do you think you can add that to the plugin?

**Comment by rikschennink** [comment]
I'm not sure what you mean by "uploader instance" can you elaborate?

**Comment by lekoala** [comment]
sure. currently the fileRenameFunction gets one argument : a file object with 3 keys. But it is impossible to know which uploader triggered the function. So if I have two uploaders on the same page, with different renaming rules, I have to define a function for each of them. I'd like to have some kind of ability to set a renaming pattern instead on the uploader (maybe in a data attribute) but for that, I need to know which uploader is triggering the renaming.

**Comment by rikschennink** [comment]
Thanks for the additional information. I think you can solve it like so. Set up the function like this ( a function returning a function )

```js
createFileRenamer = (pond) => (file) => {
    return `my_new_name${file.extension}`;
}
```

Now you can do this

```js
const pond = FilePond.create();
pond.fileRenameFunction = createFileRenamer(pond);
```

**Comment by lekoala** [comment]
indeed ! that's a very good suggestion! thanks :-)
