### ISSUE TITLE
Handle promise return

### ISSUE THREAD

**Issue by fbruffaert** [pqina/filepond-plugin-file-rename#3]
Hello,

Is there a possibility to implement a `fileRenameFunction` that would return a promise, instead of the string filename?

Use case : I open a dialog box for the user to type the desired file name, which introduce asynchronous operations.

Thanks

**Comment by rikschennink** [comment]
Hmm hadn't thought of this use case (which is foolish of me because it's not that exotic :D), I'll see if I can update this in the next version.

**Comment by rikschennink** [comment]
Just published version `1.1.0` of the plugin. You can now return a promise.

```js
fileRenameFunction: file => new Promise(resolve => {
  resolve(window.prompt('Enter new filename', file.name));
});
```

**Comment by fbruffaert** [comment]
Just tested it. Works great. Thanks for your prompt response!

**Comment by rikschennink** [comment]
Fantastic, glad to hear that :-)

**Comment by Gabiruti** [comment]
This is working on angular?
