### ISSUE TITLE
Filepond peer dependency upgrade

### ISSUE THREAD

**Issue by xvvvyz** [pqina/filepond-plugin-file-rename#4]
Hello. Thank you x100 for your work on Filepond. It's awesome.

Is there any reason the `filepond` peerDependency is set to `^1.8.0`? Can it be updated to the latest? I can make a PR if you'd like.

**Comment by rikschennink** [comment]
Thanks!

It's mostly because I assumed that would cover `1.8.x` to `x.x.x` but it apparently doesn't :-)

Change to `>=1.8.x <4.x` and just published to npm.

**Comment by xvvvyz** [comment]
Rad! Closing.
