### ISSUE TITLE
keep image preview on deleteFailure

### ISSUE THREAD

**Issue by Ganjdast** [pqina/filepond-plugin-file-rename#6]
Hello, I 'm using image preview plugin, I want to handle delete failure in a way to keep image-preview element. when I do not call load method it will keep the image ,but the remove icon is changed to upload again and remove button is moved to left side of the container,
and then when I click the remove button for the second time(the one on the left side), 
it will remove the file.

I would appreciate if some one could tell me how to keep the toolbar like uploadComplete state

**Comment by rikschennink** [comment]
I'm sorry I do not understand what you're trying to accomplish, I also fail to see the relation to the filepond-plugin-file-rename repository.

**Comment by Ganjdast** [comment]
sorry I commented on the wrong repository, it should be under image-preview category.
and I found another issue like mine ,I had a problem handling error when deleting image ,and found that "ToDo" part in your code ,so I close this issue
thanks again
